### ISSUE TITLE
All the metrics in gluster prometheus should have a Cluster Id (any unique identifier)

### ISSUE THREAD

**Issue by cloudbehl** [gluster/gluster-prometheus#14]
RHGSWA - supports multi-cluster scenario so this will need the unique identifier.

**Comment by labazza** [comment]
i achieve this grouping by the cluster by job so that the job label is equal to my cluster?

**Comment by aravindavk** [comment]
> i achieve this grouping by the cluster by job so that the job label is equal to my cluster?

Is job label set while starting the glusterd pods? Please provide more information about setting up the job label.

**Comment by labazza** [comment]
in Prometheus the "job" label is available for free so what i do to create a different job for every cluster.
As the label "instance" is considered a gluster node for me.
This is part of my prometheus config file:
```
- job_name: glustercl101
  static_configs:
  - targets:
    - glusterserver101:9189
    - glusterserver102:9189
    - glusterserver103:9189
- job_name: glustercl201
  static_configs:
  - targets:
    - glusterserver201:8080
    - glusterserver2028080
    - glusterserver203:8080
- job_name: glustercl301
  static_configs:
  - targets:
    - glusterserver301:9189
    - glusterserver302:9189
    - glusterserver303:9189
```
